#
# TIM BUCHALKA'S COMPLETE PYTHON MASTERCLASS Created by Tim Buchalka, Jean-Paul Roberts, Tim Buchalka's Learn Programming Academy.
# This is a collection of my codes, generated by myself for learning Python T
# his challenge is about understanding shelves in Python.
# Here is a link to the course: https://www.udemy.com/python-the-complete-python-developer-course/
# START OF CHALLENGE (TIM BUCHALKA)
#
# START OF MY OWN CODE


import shelve

# V1
vocabulary = shelve.open("vocabulary")
print("for key in vocabulary:")
print("    print(vocabulary[key])")
for key in vocabulary:
    print(vocabulary[key])
print("")

# V2
print("for shelf_key in vocabulary:")
print("    print(vocabulary.get(shelf_key))")
for shelf_key in vocabulary:
    print(vocabulary.get(shelf_key))
# Both V1 and V2 leading to printing out each element of these shelves/dictionaries.
# The goal is to print them out one by one.

# while True:
#     dict_key = input("Please enter a direction: ")
#     if dict_key == "quit":
#         break
#
#     if dict_key in vocabulary:
#         direction = vocabulary.get(dict_key)
#         print(direction)

print("")
print("ordered_vocabulary = list(vocabulary)")
print("ordered_vocabulary.sort()")
print("ordered_vocabulary")
ordered_vocabulary = list(vocabulary)
ordered_vocabulary.sort()
print(ordered_vocabulary)

print("")
print("for v in vocabulary.values():")
print("    print(v)")
print("print(vocabulary.values())")
for v in vocabulary.values():
    print(v)
print(vocabulary.values())

print("")
print("for f in vocabulary.items():")
print("    print(f)")
print("print(vocabulary.items())")
for f in vocabulary.items():
    print(f)
print(vocabulary.items())

print("")
print("print(vocabulary)")
print("for direction in vocabulary:")
print("    print(direction, vocabulary[direction])")
print(vocabulary)
for direction in vocabulary:
    print(direction, vocabulary[direction])

print("")
print("print(vocabulary['vocabulary'])")
print(vocabulary["vocabulary"])

print("")
print("print(vocabulary['vocabulary']['QUIT'])")
print(vocabulary["vocabulary"]["QUIT"])

print("")
print("print(vocabulary['vocabulary']['SOUTH'])")
print(vocabulary["vocabulary"]["SOUTH"])

print("")
print("print(vocabulary['vocabulary']['EAST'])")
print(vocabulary["vocabulary"]["EAST"])

print("")
print("print(vocabulary['vocabulary']['WEST'])")
print(vocabulary["vocabulary"]["WEST"])

print("")
print("print(vocabulary['vocabulary']['ROAD'])")
print(vocabulary["vocabulary"]["ROAD"])

print("")
print("print(vocabulary['vocabulary']['HILL'])")
print(vocabulary["vocabulary"]["HILL"])

print("")
print("print(vocabulary['vocabulary']['BUILDING'])")
print(vocabulary["vocabulary"]["BUILDING"])

print("")
print("print(vocabulary['vocabulary']['ROAD'])")
print(vocabulary["vocabulary"]["ROAD"])

print("")
print("print(vocabulary['vocabulary']['VALLEY'])")
print(vocabulary["vocabulary"]["VALLEY"])

print("")
print("print(vocabulary['vocabulary']['FOREST'])")
print(vocabulary["vocabulary"]["FOREST"])

print("")
print("")
print("")

vocabulary_forest = vocabulary["vocabulary"]["FOREST"]
print(vocabulary_forest)
vocabulary.close()
